### ISSUE TITLE
Huge ram consumption

### ISSUE THREAD

**Issue by natir** [YannGarbe/PFE_2018#2]
The project has a very large memory consumption at the moment that I have trouble explaining.

Do you have any ideas:
- Why project use all this ram ?
- How to reduce this memory cost ?

**Comment by YannGarbe** [comment]
Does this ram problem concern all the analyses? Or only strict/max/custom (not gentle)?

**Comment by YannGarbe** [comment]
I have two ideas :
- The intervals dictionary is twice as big as it should be (because dict[id_a][id_b][+] == dict [id_b][id_a][+]). I have an idea to reduce its size and I'll implement it this evening.
- The coverage arrays can consume a lot of memory in my opinion. I don't have a solution a this moment, but I think the problem is the use of the coverage method itself.

**Comment by natir** [comment]
I just test with gentle mode. coverage array canu use more than 256 GB ?
